id: I995FF7CE
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3878final
source_file: null
initial_creation_type: input
imported: '2022-08-01T10:46:33.163465'
last_modified: '2022-08-01T10:46:33.163475'
parser: null
source_metadata:
  title: Commentary
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
